typography_spectrum: 0.31734
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2232613991945982
  lightness: 0.0018911552615463734
  saturation: 0.8696735324338078
  rhythmicContrast: 0.04923208290711045
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11323608038946986
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Kaleb Barker
  email: kalebbarker@gmail.com
  url: kalebbarker.com
name: Kaleb Barker
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
